name: luacheck
on: 
  push:
    paths:
      - '**.lua'
      - '.github/workflows/**.yml'
  pull_request:
    paths:
      - '**.lua'
      - '.github/workflows/**.yml'
jobs:
  luacheck:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Luacheck
        uses: lunarmodules/luacheck@master
