name: mtt
on: 
  push:
    paths:
      - '**.lua'
      - '.github/workflows/**.yml'
  pull_request:
    paths:
      - '**.lua'
      - '.github/workflows/**.yml'
jobs:
  mtt:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: buckaroobanzay/mtt@main
      with:
        modname: technic
        git_dependencies: |
          https://github.com/mt-mods/basic_materials.git
          https://github.com/mt-mods/pipeworks.git
          https://github.com/OgelGames/fakelib.git
          https://github.com/minetest-mods/moreores.git
          https://github.com/mt-mods/xcompat.git
